services:
  dex:
    image: ghcr.io/enopax/dex:2.45.1_file_store
    command: ["dex", "serve", "/etc/dex/dex.yaml"]
    ports:
      - "5556:5556"
      - "5557:5557"
    volumes:
      - ./dex-dev.yaml:/etc/dex/dex.yaml:ro
      - dex-data:/data

volumes:
  dex-data:
